### ISSUE TITLE
Connectivity-dns can serve DNS A records based on EndpointSlices

### ISSUE THREAD

**Issue by christianang** [vmware-tanzu/cross-cluster-connectivity#37]
## Description

To support serving wildcard records for a gateway it would be valuable to have a CRD that I can create to define an A record that the DNS server can serve to anyone attempting to resolve a service on that gateway.

## Desired Solution

I can create a `DNSARecord` resource in the namespace that connectivity-dns is watching.

```yaml
kind: DNSARecord
metadata:
  name: strawberry-gateway
spec:
  hostname: *.gateway.strawberry.clusters.global
  backends:
  - host: 10.4.5.6
  - host: 10.4.5.7
```

Assuming my in-cluster dns has been configured to route requests for `*.gateway.strawberry.clusters.global` to the connectivity-dns server, then I can resolve `foo.gateway.strawberry.clusters.global` to `{10.4.5.6,10.4.5.7}`.

**Comment by rosenhouse** [comment]
First part of #38

**Comment by jamiemonserrate** [comment]
@christianang @rosenhouse - Maybe we could use [Endpoint Slices](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices) instead of creating our own CRD? It _seems_ that it can represent all of the information we are looking to hold.

**Comment by rosenhouse** [comment]
I was surprised to learn that the EndpointSlice `metadata.name` can include `.`.  This is nice.

**Comment by rosenhouse** [comment]
But can EndpointSlice's `metadata.name` include `*`?  If not, then....

**Comment by rosenhouse** [comment]
If we go with EndpointSlice, then either the DNS server needs to be "smart" and prepend the `*`, or we could require an annotation to convey the desired DNS name, e.g.

```
kind: EndpointSlice
metadata:
  name: whatever
  annotations:
    xcc/dns-a-record: "*.gateway.strawberry.foo-team.clusters.global"
```
