### ISSUE TITLE
Lifecycle-manage EndpointSlices on workload clusters for each LoadBalancer-fronted gateway

### ISSUE THREAD

**Issue by rosenhouse** [vmware-tanzu/cross-cluster-connectivity#43]
With #42 we now have a way to serve DNS records from within a workload cluster, based on annotated `EndpointSlices` in that cluster's API server.

Here we'll automate the creation of those annotated-`EndpointSlices` on all clusters, based on state in the management cluster.

We'll scope this just to gateways fronted by `Service` `type:LoadBalancer`

New CRD:

```yaml
# lives in the management cluster, in the same namespace as the Cluster it refs
apiVersion: connectivity.tanzu.vmware.com/v1alpha1
kind: GatewayDNSRecord
metadata:
  name: strawberry-gateway
  namespace: foo-team
spec:
  cluster: strawberry
  namespace: projectcontour
  service: envoy
  resolutionType: loadBalancer
```

New controller:
- For each GatewayDNSRecord G
  - Use Cluster API to log in to the ref'd cluster (e.g. `strawberry`) and discover the public IP address of the ref'd load-balancer service
  - Render an annotated `EndpointSlice`, sufficient to drive DNS resolution via #42
- For each workload cluster C
   - ensure there's a copy of that `EndpointSlice` in the cluster's apiserver

The EndpointSlices would look like
```yaml
# one of these on every managed workload cluster
kind: EndpointSlice
metadata:
  name: foo-team-strawberry-gateway
  namespace: capi-dns
  annotations:
    connectivity.tanzu.vmware.com/dns-hostname:
      "*.gateway.strawberry.foo-team.clusters.internal"

addressType: IPv4
endpoints:
- addresses:
  - "<LB IP addr>"
```

Handle updates/deletes as well.

**Comment by rosenhouse** [comment]
Notes from team discussion:
- We'll want to change the EndpointSlice DNS server to only watch 1 namespace (e.g. `capi-dns`), not all
- We'll probably want the installation of that DNS server to be what creates the `capi-dns` namespace.  Creating the namespace shouldn't be the responsibility of this controller

**Comment by christianang** [comment]
Notes from team discussion:

* Changing the data model to use a `clusterSelector` instead of the name of the cluster. This is a one to many relationship between the CRD and the clusters. This seems useful because we imagine that the gateway may be deployed similarly on many clusters and repeating that information for each CR is not useful.

```yaml
apiVersion: connectivity.tanzu.vmware.com/v1alpha1
kind: GatewayDNS
metadata:
  name: contour-clusters
  namespace: foo-team
spec:
  clusterSelector:
    matchLabel:
      hasContour: true 
  namespace: projectcontour
  service: envoy
  resolutionType: hostPort
```
