### ISSUE TITLE
EndpointSlices for hostPort DaemonSet gateways

### ISSUE THREAD

**Issue by rosenhouse** [vmware-tanzu/cross-cluster-connectivity#44]
Similar to #43, but when the ingress gateway is listening on host ports as a DaemonSet

```yaml
# lives in the management cluster, in the same namespace as the Cluster it refs
apiVersion: connectivity.tanzu.vmware.com/v1alpha1
kind: GatewayDNSRecord
metadata:
  name: strawberry-gateway
  namespace: foo-team
spec:
  cluster: strawberry
  namespace: projectcontour
  service: envoy
  resolutionType: hostPort
```

For now we can **assume the gateway proxies are running on every worker node**.

The EndpointSlices would look like
```yaml
# one of these on every managed workload cluster
kind: EndpointSlice
metadata:
  name: foo-team-strawberry-gateway
  namespace: capi-dns
  annotations:
    connectivity.tanzu.vmware.com/dns-hostname:
      "*.gateway.strawberry.foo-team.clusters.internal"

addressType: IPv4
endpoints:
- addresses:
  - "<IP of node A for strawberry cluster>"
  - "<IP of node B for strawberry cluster>"
  - "<IP of node C for strawberry cluster>"
```

Handle updates/deletes of the node IPs.
