### ISSUE TITLE
EndpointSlices for hostPort Deployment gateways

### ISSUE THREAD

**Issue by rosenhouse** [vmware-tanzu/cross-cluster-connectivity#45]
Similar to #44, but when the gateway proxies may be running on **only a subset of worker nodes**.

```yaml
# lives in the management cluster, in the same namespace as the Cluster it refs
apiVersion: connectivity.tanzu.vmware.com/v1alpha1
kind: GatewayDNSRecord
metadata:
  name: strawberry-gateway
  namespace: foo-team
spec:
  cluster: strawberry
  namespace: projectcontour
  service: envoy
  resolutionType: hostPort
```

The EndpointSlices would look like
```diff
  # one of these on every managed workload cluster
  kind: EndpointSlice
  ...
  endpoints:
  - addresses:
    - "<IP of node A for strawberry cluster>"
-   - "<IP of node B for strawberry cluster>"
+  # no address for node B, if there isn't a gateway proxy pod running on that node
    - "<IP of node C for strawberry cluster>"
```

Handle updates/deletes when node IPs change, or when pods get rescheduled to different nodes.
