### ISSUE TITLE
Merging Endpoints for DNS from multiple EndpointSlices

### ISSUE THREAD

**Issue by christianang** [vmware-tanzu/cross-cluster-connectivity#46]
## Description
The relationship between Services and EndpointSlices is 1 to many. It would make sense that we continue this relationship with our DNS annotation e.g I can create two EndpointSlices with some set of IPs that both have the same DNS annotation and when I query that DNS hostname I get the full set of endpoints from both (or more) EndpointSlices.

## Desired Solution
I create two Endpoint Slices:
```yaml
# one of these on every managed workload cluster
kind: EndpointSlice
apiVersion: discovery.k8s.io/v1beta1
metadata:
  name: foo-team-strawberry-gateway
  namespace: xcc-dns
  annotations:
    connectivity.tanzu.vmware.com/dns-hostname: "*.gateway.strawberry.foo-team.clusters.internal"
addressType: IPv4
endpoints:
- addresses:
  - "1.2.3.4"
```
```yaml
# one of these on every managed workload cluster
kind: EndpointSlice
apiVersion: discovery.k8s.io/v1beta1
metadata:
  name: foo-team-strawberry-gateway
  namespace: xcc-dns
  annotations:
    connectivity.tanzu.vmware.com/dns-hostname: "*.gateway.strawberry.foo-team.clusters.internal"
addressType: IPv4
endpoints:
- addresses:
  - "2.3.4.5"
```

When I query `foo.gateway.strawberry.foo-team.clusters.internal` then I get back both `1.2.3.4` and `2.3.4.5`.

## Additional Context
The initial PR for EndpointSlices: #42
